apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
spec:
  ingressClassName: nginx
  rules:
    - host: app.carsties.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auction-clusterip
                port:
                  number: 80
    - host: id.carsties.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-clusterip
                port:
                  number: 80

    - host: api.carsties.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-clusterip
                port:
                  number: 80
