apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-svc
spec:
  selector:
    matchLabels:
      app: bid-svc
  template:
    metadata:
      labels:
        app: bid-svc
    spec:
      containers:
        - name: bid-svc
          image: trycatchlearn/bid-svc:latest
          env:
            - name: ConnectionStrings__BidDbConnection
              valueFrom:
                secretKeyRef:
                  name: bid-secret
                  key: connString
            - name: RabbitMQ__USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: username
            - name: RabbitMQ__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: password
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: bid-svc-config
---
apiVersion: v1
kind: Service
metadata:
  name: bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: bid-svc
  ports:
    - port: 80
      targetPort: 80
