name: Build and publish

on:
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: 'kino2001/auction-svc'
            path: 'src/AuctionService'

          - name: 'kino2001/bid-svc'
            path: 'src/BiddingService'

          - name: 'kino2001/gateway-svc'
            path: 'src/GatewayService'

          - name: 'kino2001/identity-svc'
            path: 'src/IdentityService'

          - name: 'kino2001/notify-svc'
            path: 'src/NotificationService'

          - name: 'kino2001/search-svc'
            path: 'src/SearchService'

          - name: 'kino2001/webapp'
            path: 'frontend/web-app'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.service.path }}/Dockerfile
          push: true
          tags: ${{ matrix.service.name }}:latest
