name: Build and publish

on:
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      continue: 'false'
    strategy:
      matrix:
        service:
          - name: 'kino2001/auction-svc'
            path: 'src/AuctionService'

          - name: 'kino2001/bid-svc'
            path: 'src/BiddingService'

          - name: 'kino2001/gateway-svc'
            path: 'src/GatewayService'

          - name: 'kino2001/identity-svc'
            path: 'src/IdentityService'

          - name: 'kino2001/notify-svc'
            path: 'src/NotificationService'

          - name: 'kino2001/search-svc'
            path: 'src/SearchService'

          - name: 'kino2001/webapp'
            path: 'frontend/web-app'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes in service path
        run: |
          if git diff --quiet HEAD^ HEAD -- ${{ matrix.service.path }}; then
            echo "No changes in ${{ matrix.service.path }}. skipping build."
            echo "continue=false" >> $GITHUB_ENV
          else
            echo "Changes detected in ${{ matrix.service.path }}. Proceeding with build."
            echo "continue=true" >> $GITHUB_ENV
          fi

      - name: Set up Docker buildx
        if: env.continue == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker
        if: env.continue == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: env.continue == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.service.path }}/Dockerfile
          push: true
          tags: ${{ matrix.service.name }}:latest
